# Generated by Django 5.0.6 on 2024-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=130)),
                ("image", models.ImageField(upload_to="resume")),
            ],
        ),
    ]
