# Generated by Django 5.0.6 on 2024-06-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram", models.CharField(max_length=100)),
                ("twitter", models.CharField(max_length=100)),
                ("instagram", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
