# Generated by Django 5.0.6 on 2024-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactus_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
            ],
        ),
    ]
