# Generated by Django 5.0.6 on 2024-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactus_app", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="call",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="email2",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
