# Generated by Django 5.0.6 on 2024-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contactus_app",
            "0004_info_remove_message_address_remove_message_call_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="age",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="call",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
